### ISSUE TITLE
好像有问题。不能启动

### ISSUE THREAD

**Issue by maxiaoxian** [shenghy/jspangAdmin#7]
$ npm run dev

> pangadmin@1.0.0 dev D:\workspace\demo\jspangAdmin
> node build/dev-server.js

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at Server.listen (net.js:1476:7)
    at Function.listen (D:\workspace\demo\jspangAdmin\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> (D:\workspace\demo\jspangAdmin\build\dev-server.js:71:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pangadmin@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pangadmin@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\crazyHC\AppData\Roaming\npm-cache\_logs\2018-03-22T00_37_45_649Z-debug.log

**Comment by ddddderek** [comment]
看看是否是本地已经开了一个8080端口
